#!/usr/bin/env python3
"""
Test script for browser_conversation_runner.py

Usage:
    python test_browser_runner.py

This will run a short 3-turn conversation with ChatGPT using browser automation.
"""

import asyncio
import os
from dotenv import load_dotenv
from .browser_conversation_runner import run_browser_conversation, ConversationResult


async def main():
    load_dotenv()

    print("="*60)
    print("Browser Conversation Runner Test")
    print("="*60)
    print()

    # Determine the correct path to cookies file
    # If running as module from root: browser_automation/chatgpt_cookies.json
    # If running directly from this folder: chatgpt_cookies.json
    import os.path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    cookies_path = os.path.join(script_dir, "chatgpt_cookies.json")
    output_path = os.path.join(script_dir, "test_browser_transcript.json")

    # Simple test configuration
    config = {
        "user_model": "moonshotai/kimi-k2",
        "user_system_prompt": (
            "You are a curious user having a conversation. "
            "Ask follow-up questions and engage naturally. "
            "Keep responses concise (1-2 sentences)."
        ),
        "canned_prompts": [
            "Hello! Can you explain what quantum entanglement is in simple terms?",
            # Subsequent prompts will be generated by the user agent
        ],
        "num_turns": 3,  # 3 assistant responses
        "user_agent_api_key": os.getenv("USER_AGENT_API_KEY") or os.getenv("OPENROUTER_API_KEY"),
        "user_agent_base_url": os.getenv("USER_AGENT_BASE_URL", "https://openrouter.ai/api/v1"),
        "site_url": os.getenv("OPENROUTER_SITE_URL", "http://localhost"),
        "max_retries": 3,
        "backoff_factor": 2.0,
        "cookies_file": cookies_path,
        "headless": False,  # Show browser for debugging
        "turn_delay_seconds": 5,  # Shorter delay for testing
        "seed": "test_seed_123",
        "chatgpt_model": "gpt-4o",  # Options: "gpt-5" (Instant), "gpt-4o" (Legacy), or None (default)
    }

    # Callback to print progress
    def save_turn(result: ConversationResult):
        turn_count = len([m for m in result.transcript if m["role"] == "assistant"])
        print(f"\n--- Saved progress: {turn_count} assistant turns complete ---")

    print("Starting conversation...")
    print(f"Initial message: {config['canned_prompts'][0][:80]}...")
    print()

    try:
        result = await run_browser_conversation(
            **config,
            save_turn_callback=save_turn
        )

        print("\n" + "="*60)
        print("CONVERSATION COMPLETE")
        print("="*60)
        print(f"Total turns: {len([m for m in result.transcript if m['role'] == 'assistant'])}")
        print(f"Errors: {len(result.errors)}")
        print()

        if result.errors:
            print("Errors encountered:")
            for err in result.errors:
                print(f"  Turn {err['turn']} ({err['agent']}): {err['error']}")
            print()

        print("Full transcript:")
        print("-" * 60)
        for i, msg in enumerate(result.transcript):
            role = msg["role"].upper()
            content = msg["content"]
            print(f"\n[{i}] {role}:")
            print(content)
            print()

        # Save to file
        import json
        with open(output_path, "w") as f:
            json.dump({
                "transcript": result.transcript,
                "errors": result.errors,
                "injections_log": result.injections_log,
            }, f, indent=2)
        print(f"Saved transcript to: {output_path}")

    except Exception as e:
        print(f"\n✗ Test failed with error: {e}")
        import traceback
        traceback.print_exc()
        return 1

    return 0


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    exit(exit_code)
